### ISSUE TITLE
Сделай неактивное состояние кнопок, а не просто белое 

### ISSUE THREAD

**Issue by rudnitskih** [mysterious25/sports-app-landing#29]
![image](https://user-images.githubusercontent.com/8848858/56884514-b52dbb80-6a72-11e9-80d5-1de755c62306.png)

Таже сделай их круглыми а не овалами

**Comment by mysterious25** [comment]
@rudnitskih не до конца понял этот таск. Но добавил хавер эффект, а круги у меня должны быть ровными( 
![image](https://user-images.githubusercontent.com/21346502/56888250-3473bd00-6a7c-11e9-9f05-cd259cfbeca4.png)

**Comment by rudnitskih** [comment]
Это особенность macos походу:

Добавь `padding: 0;` для кнопки

**Comment by rudnitskih** [comment]
Явно задай цвет для активной и неактивной кнопки:

![image](https://user-images.githubusercontent.com/8848858/56888549-ed39fc00-6a7c-11e9-832f-b84833cd6f25.png)

**Comment by rudnitskih** [comment]
просто если не задать то будут применяться дефолтные стили браузера для тега `button`

**Comment by mysterious25** [comment]
@rudnitskih  сделал, пришлось всё же импортентом воспользоваться, чтоб перебить стили библиотеки
