### ISSUE TITLE
Move everything what related to libs into separate folder as sibling to src 

### ISSUE THREAD

**Issue by rudnitskih** [mysterious25/sports-app-landing#31]
![image](https://user-images.githubusercontent.com/8848858/56885114-55d0ab00-6a74-11e9-86dd-a90e52e05cec.png)

**Comment by rudnitskih** [comment]
не совесем так, sibling - это сосед 

Посмотри как у других сделано: https://github.com/dimavasilenko/sports-app-landing

**Comment by mysterious25** [comment]
@rudnitskih готово, создал директорию lib
