### ISSUE TITLE
Empty element

### ISSUE THREAD

**Issue by rudnitskih** [mysterious25/sports-app-landing#32]
![image](https://user-images.githubusercontent.com/8848858/56885164-71d44c80-6a74-11e9-8c34-bf2aee1cd498.png)

**Comment by rudnitskih** [comment]
я думал ты его заполнишь :)

![image](https://user-images.githubusercontent.com/8848858/56890408-05604a00-6a82-11e9-8a31-04aaf7d25ceb.png)

**Comment by mysterious25** [comment]
@rudnitskih  Добавил текст)
